name: Output Demo
on: push
jobs:
  build:
    outputs:
      ver: ${{ steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT #this is an file to store in github
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "We are deploy the app with version ${{ needs.build.outputs.ver }}"
